<?php

function simplesitemap_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_type_edit_form') {

    $content_types = \Drupal::config('simplesitemap.settings')->get('content_types');

    $form['simplesitemap'] = array(
      '#group' => 'additional_settings',
      '#title' => 'Simple XML sitemap',
      '#type' => 'details'
    );

    $index_content_checked = isset($content_types[$form['type']['#default_value']]['index']) ? $content_types[$form['type']['#default_value']]['index'] : FALSE;
    $form['simplesitemap']['simplesitemap_index_content'] = array(
      '#type' => 'checkbox',
      '#title' => 'Index content of this type',
      '#default_value' => $index_content_checked,
    );

    $priority = isset($content_types[$form['type']['#default_value']]['priority']) ? $content_types[$form['type']['#default_value']]['priority'] : 0.5;
    $form['simplesitemap']['simplesitemap_priority'] = array(
      '#type' => 'select',
      '#title' => 'Priority',
      '#default_value' => $priority,
      '#description' => 'The priority nodes of this content type will have in the eyes of search engine bots.',
    );
    foreach(range(0, 10) as $value) {
      $value = $value / 10;
      $options[(string)$value] = (string)$value;
    }
    $form['simplesitemap']['simplesitemap_priority']['#options'] = $options;

    $form['actions']['submit']['#submit'][] = 'simplesitemap_bundle_form_submit';
  }
}

function simplesitemap_bundle_form_submit($form, &$form_state) {
  $values = $form_state->getValues();
  $config = \Drupal::service('config.factory')->getEditable('simplesitemap.settings');
  $content_types = $config->get('content_types');
  $content_types[$form['type']['#default_value']]['index'] = $values['simplesitemap_index_content'];
  $content_types[$form['type']['#default_value']]['priority'] = $values['simplesitemap_priority'];
  $config->set('content_types', $content_types)->save();
}
