<?php
/**
 * @file
 * Main module file containing hooks.
 */

use Drupal\simplesitemap\Simplesitemap;

/**
 * Implements hook_form_alter.
 */
function simplesitemap_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_type_edit_form') {

    $sitemap = new Simplesitemap;

    // Get current content type sitemap settings.
    $content_types = $sitemap->get_content_types();

    $form['simplesitemap'] = array(
      '#group' => 'additional_settings',
      '#title' => 'Simple XML sitemap',
      '#type' => 'details'
    );

    $index_content_checked = isset($content_types[$form['type']['#default_value']]['index']) ? $content_types[$form['type']['#default_value']]['index'] : FALSE;
    $form['simplesitemap']['simplesitemap_index_content'] = array(
      '#type' => 'checkbox',
      '#title' => 'Index content of this type',
      '#default_value' => $index_content_checked,
    );

    $priority = isset($content_types[$form['type']['#default_value']]['priority']) ? $content_types[$form['type']['#default_value']]['priority'] : $sitemap->get_priority_default();
    $form['simplesitemap']['simplesitemap_priority'] = array(
      '#type' => 'select',
      '#title' => 'Priority',
      '#options' => $sitemap->get_priority_select_values(),
      '#default_value' => $priority,
      '#description' => 'The priority nodes of this content type will have in the eyes of search engine bots.',
    );

    // Add submission handler.
    $form['actions']['submit']['#submit'][] = 'simplesitemap_bundle_form_submit';
  }
}

/**
 * Form submission handler callback.
 */
function simplesitemap_bundle_form_submit($form, &$form_state) {
  $values = $form_state->getValues();

  // Only make changes in DB if sitemap settings actually changed.
  if ($form['simplesitemap']['simplesitemap_index_content']['#default_value'] != $form['simplesitemap']['simplesitemap_index_content']['#value'] || $form['simplesitemap']['simplesitemap_priority']['#default_value'] != $form['simplesitemap']['simplesitemap_priority']['#value']) {

    $sitemap = new Simplesitemap;

    // Get current content type sitemap settings.
    $content_types = $sitemap->get_content_types();

    $content_types[$form['type']['#default_value']]['index'] = $values['simplesitemap_index_content'];
    $content_types[$form['type']['#default_value']]['priority'] = $values['simplesitemap_priority'];

    // Save new content type settings.
    $sitemap->save_content_types($content_types);

    // Regenerate sitemaps for all languages and save them into strings for performance reason (pseudo caching).
    $sitemap->generate_all_sitemaps();
  }
}

/**
 * Implements hook_cron.
 */
function simplesitemap_cron() {

  // Regenerate sitemaps for all languages and save them into strings for performance reasons (pseudo caching).
  $sitemap = new Simplesitemap;
  $sitemap->generate_all_sitemaps();
}

