simplesitemap.settings:
  type: config_object
  mapping:
    settings:
      type: mapping
      mapping:
        max_links:
          label: 'Max Links'
          type: integer
        cron_generate:
          label: 'Cron Generate'
          type: boolean
    custom:
      label: 'Custom'
      type: sequence
      sequence:
        type: mapping
        mapping:
          path:
            label: 'Path'
            type: string
          priority:
            label: 'Priority'
            type: float
    entity_types:
      label: 'Entity Types'
      type: sequence
      sequence:
        type: sequence
        sequence:
          type: mapping
          mapping:
            index:
              label: 'Index'
              type: integer
            priority:
              label: 'Priority'
              type: float
